# Site settings
title: The OPEN
email: jason@10layer.com
description: > # this means to ignore newlines until "baseurl:"
  OPEN is more than just an office. It's a collaborative community of creative and professional people to come together in an inspiring and diverse space where you can expand your mind, meet, network and collaborate. Whether you’re an individual or a business, explore the new frontier of collaborative shared office space.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://open.co.za" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
